### ISSUE TITLE
Error happens when examples run

### ISSUE THREAD

**Issue by vence722** [lxn/walk#103]
I tried to run the examples in 'github.com/lxn/walk/examples' using both 'go run _**,go' and  'go build *_*.go', but it failed. The message is following:

C:\Go\src\pkg\github.com\lxn\walk\examples\clipboard>go run clipboard.go
2014/05/14 21:51:39 TTM_ADDTOOL failed

Stack:
C:/Go/src/pkg/github.com/lxn/walk/error.go:79 (0x4353b1)
        com/lxn/walk.newErr: return &Error{message: message, stack: debug.Stack(
)}
C:/Go/src/pkg/github.com/lxn/walk/error.go:83 (0x4354b4)
        com/lxn/walk.newError: return processError(newErr(message))
C:/Go/src/pkg/github.com/lxn/walk/tooltip.go:115 (0x44e36a)
        com/lxn/walk.(_ToolTip).AddTool: return newError("TTM_ADDTOOL failed")
C:/Go/src/pkg/github.com/lxn/walk/widget.go:106 (0x451d0d)
        com/lxn/walk.(_WidgetBase).init: if err := globalToolTip.AddTool(wb); er
r != nil {
C:/Go/src/pkg/github.com/lxn/walk/window.go:396 (0x4546d9)
        com/lxn/walk.InitWindow: if err := wb.init(widget); err != nil {
C:/Go/src/pkg/github.com/lxn/walk/widget.go:85 (0x451b09)
        com/lxn/walk.InitWidget: if err := InitWindow(widget, parent, className,
 style|win.WS_CHILD, exStyle); err != nil {
C:/Go/src/pkg/github.com/lxn/walk/composite.go:31 (0x431c5d)
        com/lxn/walk.newCompositeWithStyle: win.WS_EX_CONTROLPARENT); err != nil
 {
C:/Go/src/pkg/github.com/lxn/walk/composite.go:39 (0x431d7d)
        com/lxn/walk.NewComposite: return newCompositeWithStyle(parent, 0)
C:/Go/src/pkg/github.com/lxn/walk/form.go:78 (0x4367e7)
        com/lxn/walk.(*FormBase).init: if fb.clientComposite, err = NewComposite
(form); err != nil {
C:/Go/src/pkg/github.com/lxn/walk/window.go:388 (0x454634)
        com/lxn/walk.InitWindow: if err := fb.init(form); err != nil {
C:/Go/src/pkg/github.com/lxn/walk/mainwindow.go:37 (0x43d931)
        com/lxn/walk.NewMainWindow: win.WS_EX_CONTROLPARENT); err != nil {
C:/Go/src/pkg/github.com/lxn/walk/declarative/mainwindow.go:37 (0x4715bb)
        com/lxn/walk/declarative.MainWindow.Create: w, err := walk.NewMainWindow
()
C:/Go/src/pkg/github.com/lxn/walk/declarative/mainwindow.go:108 (0x471b87)
        com/lxn/walk/declarative.MainWindow.Run: if err := mw.Create(); err != n
il {
C:/Go/src/pkg/github.com/lxn/walk/examples/clipboard/clipboard.go:46 (0x4013f0)
        main: }).Run(); err != nil {
C:/Users/ADMINI~1/AppData/Local/Temp/2/makerelease155988687/go/src/pkg/runtime/p
roc.c:220 (0x415d62)
C:/Users/ADMINI~1/AppData/Local/Temp/2/makerelease155988687/go/src/pkg/runtime/p
roc.c:1394 (0x418460)
exit status 1

I'm using a laptop on 64-bit Windows 7 OS.

**Comment by shawnye** [comment]
You must copy `rsrc.syso` to your working dir

**Comment by StephanVerbeeck** [comment]
Sorry but could somebody please change the provided example so that it can be used as an example.
Because currently it doesn't work and explaining #28 how to fix it will be a repetitive task if the provided examples don't use this.


https://github.com/lxn/walk/blob/master/examples/filebrowser/filebrowser.go

C:\Build\experiment\go\walkGUIexamples\filebrowser>go version

	go version go1.12.5 windows/amd64

C:\Build\experiment\go\walkGUIexamples\filebrowser>go clean -cache

C:\Build\experiment\go\walkGUIexamples\filebrowser>go build

C:\Build\experiment\go\walkGUIexamples\filebrowser>filebrowser.exe

	2019/05/23 08:01:04 TTM_ADDTOOL failed

	Stack:
	goroutine 1 [running, locked to thread]:
	runtime/debug.Stack(0x432, 0x0, 0xc00008c760)
			C:/Go/src/runtime/debug/stack.go:24 +0xa4
	github.com/lxn/walk.newErr(...)
			C:/Users/Stephan/go/src/github.com/lxn/walk/error.go:81
	github.com/lxn/walk.newError(0x6b473c, 0x12, 0x0, 0xc00008c760)
			C:/Users/Stephan/go/src/github.com/lxn/walk/error.go:85 +0x2e
	github.com/lxn/walk.(*ToolTip).addTool(0xc0000be000, 0x704ec0, 0xc0000d4000, 0xc00008c800, 0xc00008c808, 0x409c31)
			C:/Users/Stephan/go/src/github.com/lxn/walk/tooltip.go:201 +0xee
	github.com/lxn/walk.(*ToolTip).AddTool(...)
			C:/Users/Stephan/go/src/github.com/lxn/walk/tooltip.go:179
	github.com/lxn/walk.(*WidgetBase).init(0xc0000d4000, 0x7030c0, 0xc0000d4000, 0x7030c0, 0xc0000d4000)
			C:/Users/Stephan/go/src/github.com/lxn/walk/widget.go:130 +0x9c
	github.com/lxn/walk.InitWindow(0xda45a8, 0xc0000d4000, 0x6ffd00, 0xc000048700, 0x6b8996, 0x1c, 0x1000050000000, 0x0, 0x0)
			C:/Users/Stephan/go/src/github.com/lxn/walk/window.go:475 +0x2ca
	github.com/lxn/walk.InitWidget(0x7030c0, 0xc0000d4000, 0x6ffd00, 0xc000048700, 0x6b8996, 0x1c, 0x1000050000000, 0x6ac360, 0x0)
			C:/Users/Stephan/go/src/github.com/lxn/walk/widget.go:107 +0xc3
	github.com/lxn/walk.NewCompositeWithStyle(0x6ffd00, 0xc000048700, 0xc000000000, 0x6ffd00, 0xc000048700, 0x702780)
			C:/Users/Stephan/go/src/github.com/lxn/walk/composite.go:28 +0xdb
	github.com/lxn/walk.NewComposite(0x702780, 0xc000048700, 0xc000048700, 0x702780, 0xc000048700)
			C:/Users/Stephan/go/src/github.com/lxn/walk/composite.go:43 +0x68
	github.com/lxn/walk.(*FormBase).init(0xc000048700, 0x705640, 0xc000048700, 0x705640, 0xc000048700)
			C:/Users/Stephan/go/src/github.com/lxn/walk/form.go:110 +0x64
	github.com/lxn/walk.InitWindow(0x6ffd00, 0xc000048700, 0x0, 0x0, 0x6b8eff, 0x1d, 0x1000000cf0000, 0x0, 0x0)
			C:/Users/Stephan/go/src/github.com/lxn/walk/window.go:467 +0xa11
	github.com/lxn/walk.NewMainWindowWithName(0x0, 0x0, 0x0, 0x0, 0x0)
			C:/Users/Stephan/go/src/github.com/lxn/walk/mainwindow.go:39 +0xb7
	github.com/lxn/walk.NewMainWindow(...)
			C:/Users/Stephan/go/src/github.com/lxn/walk/mainwindow.go:32
	github.com/lxn/walk/declarative.MainWindow.Create(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
			C:/Users/Stephan/go/src/github.com/lxn/walk/declarative/mainwindow.go:60 +0x9a
	main.main()
			C:/Build/experiment/go/walkGUIexamples/filebrowser/filebrowser.go:296 +0x5ff

Compiling as a windows application -> https://www.programming-books.io/essential/go/a-first-window-app-e87631a7f8a94e8f92f9114e8e6baf0a
generic manifest -> https://raw.githubusercontent.com/essentialbooks/code/master/go/windows/app.manifest

	<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
	<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
	  <assemblyIdentity version="1.0.0.0" processorArchitecture="*" name="SomeFunkyNameHere" type="win32"/>
	  <dependency>
		<dependentAssembly>
		  <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"/>
		</dependentAssembly>
	  </dependency>
	<application xmlns="urn:schemas-microsoft-com:asm.v3">
	  <windowsSettings>
		<dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">True</dpiAware>
	  </windowsSettings>
	</application>
	<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
	  <application>
		
		<supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
		
		<supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
		
		<supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
		
		<supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
		
		<supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
	  </application>
	</compatibility>
	</assembly>
