### ISSUE TITLE
Exit app from separate thread

### ISSUE THREAD

**Issue by IaBurton** [lxn/walk#216]
Hello, thanks for the walk package, it has come in handy.

I do have a question, and maybe this is from the lack of documentation or my understanding of the Win32 api, but is there a way to exit the application from a separate thread not running the GUI?

If I call walk.App().Exit from a separate goroutine the call succeeds but the app doesn't exit. The main thread remains stuck in "Run". Meaning if I have some part of the application that's running concurrently and needs to fail, the most I can do is tell the user but I cannot exit afterwards.

As in your notifyicon example, if the Exit comes from a callback that main runs then it exits fine. Interestingly calls to creating a notification from the notifyicon work concurrently. Are there parts of the api that work concurrently and others that don't? How do I get around the exit issue (without killing the entire application with os.Exit)? Thanks

**Comment by IaBurton** [comment]
Ok so I just saw #91 and that solves the problem :smile: 

As an aside before this is closed, have you considered using golang.org/x/sys to avoid preloading dll attacks? https://github.com/golang/go/issues/14959
And using Lazy load for dlls as opposed to MustLoad so apps don't crash on start and can be recovered (especially if they do not need that dll)? Thanks again

**Comment by lxn** [comment]
Will have to give this some thought, thanks!

**Comment by tmm1** [comment]
In my experience, using `WindowBase.Synchronize()` to call `walk.App().Exit(0)` is also not reliable.

This is because the app is stuck in `GetMessage` and never receives a message to wake up when Synchronize blocks are added.

```
goroutine 1 [syscall, 4 minutes, locked to thread]:
syscall.Syscall6(0x7ffac0014830, 0x4, 0xc042395b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc042004eb8, ...)
	src/runtime/syscall_windows.go:174 +0x69
github.com/lxn/win.GetMessage(0xc042395b80, 0x0, 0x0, 0x0)
	src/github.com/lxn/win/user32.go:2202 +0x8d
github.com/lxn/walk.(*FormBase).Run(0xc0421f6e00, 0xc04207ea01)
	src/github.com/lxn/walk/form.go:366 +0xe8
```

**Comment by tmm1** [comment]
> This is because the app is stuck in GetMessage and never receives a message to wake up when Synchronize blocks are added.

Actually, `Synchronize` sends a special walkSync message to make up the loop.

It turns out this behavior was related to other broken behavior I was seeing in https://github.com/lxn/walk/issues/337, caused by a golang bug fixed for golang 1.10
