### ISSUE TITLE
XP SP3: panic: The specified procedure could not be found.

### ISSUE THREAD

**Issue by hldh214** [lxn/walk#263]
```
C:\Documents and Settings\Jim\桌面\GO\src\170419>rsrc -manifest 170419.exe.manif
est
Manifest ID:  1

C:\Documents and Settings\Jim\桌面\GO\src\170419>go build

C:\Documents and Settings\Jim\桌面\GO\src\170419>170419.exe
panic: The specified procedure could not be found.

goroutine 1 [running]:
github.com/lxn/win.MustGetProcAddress(0x5adc0000, 0x5c3c82, 0xf, 0x5adc2bef)
        C:/Documents and Settings/Jim/桌面/GO/src/github.com/lxn/win/win.go:57 +
0x5a
github.com/lxn/win.init.13()
        C:/Documents and Settings/Jim/桌面/GO/src/github.com/lxn/win/uxtheme.go:
161 +0xa7
github.com/lxn/win.init()
        C:/Documents and Settings/Jim/桌面/GO/src/github.com/lxn/win/winspool.go
:101 +0x7a
github.com/lxn/walk.init()
        C:/Documents and Settings/Jim/桌面/GO/src/github.com/lxn/walk/window.go:
1563 +0x43
main.init()
        C:/Documents and Settings/Jim/桌面/GO/src/170419/gui.go:31 +0x34

C:\Documents and Settings\Jim\桌面\GO\src\170419>go version
go version go1.8.1 windows/386

```

OS Name: Microsoft Windows XP Professional
OS Version: 5.1.2600 Service Pack 3 Build 2600

btw: code from README's `test.go` && `test.manifest`

**Comment by lxn** [comment]
I don't care for Windows versions that Microsoft doesn't support any more.

This means, don't expect XP and even Vista + related server versions to work.

**Comment by hldh214** [comment]
get it
