### ISSUE TITLE
fatal error in TreeView WndProc (nil pointer)

### ISSUE THREAD

**Issue by StephanVerbeeck** [lxn/walk#515]
case win.WM_NOTIFY:
		nmhdr := (*win.NMHDR)(unsafe.Pointer(lParam))

		switch nmhdr.Code {
		case win.TVN_GETDISPINFO:
			nmtvdi := (*win.NMTVDISPINFO)(unsafe.Pointer(lParam))
			item := tv.handle2Item[nmtvdi.Item.HItem]

			if nmtvdi.Item.Mask&win.TVIF_TEXT != 0 {
				var text string
				rc := win.RECT{Left: int32(nmtvdi.Item.HItem)}
				if 0 != tv.SendMessage(win.TVM_GETITEMRECT, 0, uintptr(unsafe.Pointer(&rc))) {
					// Only retrieve text if the item is visible. Why isn't Windows doing this for us?
					text = item.Text() // <- here it happens, (item==nil)
				}

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running, locked to thread]:

	runtime/debug.Stack(0x0, 0x0, 0x0)
		C:/build/Go/src/runtime/debug/stack.go:24 +0xa8
	main.RunMainWindow.func1()
		c:/Build/Account/Main.go:185 +0x123
	panic(0x8510a0, 0xc903b0)
		C:/build/Go/src/runtime/panic.go:522 +0x1ee
	github.com/lxn/walk.(*TreeView).WndProc(0xc0004ae700, 0x7706ee, 0xc00000004e, 0x0, 0x10febe0, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/treeview.go:518 +0x502
	github.com/lxn/walk.(*ContainerBase).WndProc(0xc00015edc0, 0x7706ee, 0xc00000004e, 0x0, 0x10febe0, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/container.go:574 +0x38b
	github.com/lxn/walk.defaultWndProc(0x7706ee, 0x4e, 0x0, 0x10febe0, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/window.go:1602 +0x106
	syscall.Syscall6(0x7ffa3c5c6880, 0x5, 0x7ffa31248580, 0x470a82, 0x1132, 0x0, 0xc0003dabc0, 0x0, 0x0, 0x0, ...)
		C:/build/Go/src/runtime/syscall_windows.go:199 +0xbd
	github.com/lxn/win.CallWindowProc(0x7ffa31248580, 0x470a82, 0xc000001132, 0x0, 0xc0003dabc0, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/win/user32.go:1925 +0xa9
	github.com/lxn/walk.(*WindowBase).WndProc(0xc0004ae700, 0x470a82, 0xc000001132, 0x0, 0xc0003dabc0, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/window.go:1922 +0x1f2
	github.com/lxn/walk.(*TreeView).WndProc(0xc0004ae700, 0x470a82, 0xc000001132, 0x0, 0xc0003dabc0, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/treeview.go:578 +0x1be
	github.com/lxn/walk.defaultWndProc(0x470a82, 0x1132, 0x0, 0xc0003dabc0, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/window.go:1602 +0x106
	syscall.Syscall6(0x7ffa3c5c5fe0, 0x4, 0x470a82, 0x1132, 0x0, 0xc0003dabc0, 0x0, 0x0, 0x0, 0x0, ...)
		C:/build/Go/src/runtime/syscall_windows.go:199 +0xbd
	github.com/lxn/win.SendMessage(0x470a82, 0xc000001132, 0x0, 0xc0003dabc0, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/win/user32.go:2766 +0x9b
	github.com/lxn/walk.(*WindowBase).SendMessage(0xc0004ae700, 0xc000001132, 0x0, 0xc0003dabc0, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/window.go:620 +0x62
	github.com/lxn/walk.(*TreeView).insertItem(0xc0004ae700, 0x2, 0x97e6e0, 0xc000339b90, 0x0, 0x0, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/treeview.go:335 +0x1e9
	github.com/lxn/walk.(*TreeView).insertChildren(0xc0004ae700, 0x97e6e0, 0xc0002baa20, 0x0, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/treeview.go:357 +0x163
	github.com/lxn/walk.(*TreeView).ensureItemAndAncestorsInserted(0xc0004ae700, 0x97e6e0, 0xc0002baa20, 0x0, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/treeview.go:434 +0x2ab
	github.com/lxn/walk.(*TreeView).SetCurrentItem(0xc0004ae700, 0x97e6e0, 0xc000339b90, 0x0, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/treeview.go:189 +0xe6
	main.RestoreDirSelection.func1()
		c:/Build/Account/Main.go:759 +0x94
	github.com/lxn/walk.runSynchronized()
		C:/Users/Stephan/go/src/github.com/lxn/walk/form.go:55 +0xf2
	github.com/lxn/walk.(*FormBase).Run(0xc0004ae380, 0x0)
		C:/Users/Stephan/go/src/github.com/lxn/walk/form.go:420 +0x46e
	main.RunMainWindow(0x0, 0x0)
		c:/Build/Account/Main.go:603 +0x54e5
	main.main()
		c:/Build/Account/Main.go:173 +0x42

The 2 functions above panic() is my error logger code (ignore those)

**Comment by lxn** [comment]
Sorry for the late response. Please try if this is fixed by https://github.com/lxn/walk/commit/b7e9b6ebb601199d10ba490a5a214348343e9150.
