### ISSUE TITLE
NotifyIcon.SetIcon() fails for stock icons

### ISSUE THREAD

**Issue by JoshuaSjoding** [lxn/walk#609]
If I call [NotifyIcon.SetIcon()](https://github.com/lxn/walk/blob/015262c282d682cc5dbff309d2b26677a0d82154/notifyicon.go#L268) with a stock icon like [IconInformation()](https://github.com/lxn/walk/blob/015262c282d682cc5dbff309d2b26677a0d82154/icon.go#L56), the call fails. This may or not be expected behavior, but it certainly caught me by surprise.

Here's a test case:

```
func main() {
	mw, err := walk.NewMainWindow()
	if err != nil {
		log.Fatal(err)
	}
	defer mw.Dispose()

	icon := walk.IconInformation()

	ni, err := walk.NewNotifyIcon(mw)
	if err != nil {
		log.Fatal(err)
	}
	defer ni.Dispose()

	// This fails
	if err := ni.SetIcon(icon); err != nil {
		log.Fatal(err)
	}
}
```

```
Stack:
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0x7fff62da6780, 0x0, 0x0)
        c:/go/src/runtime/debug/stack.go:24 +0xa4
github.com/lxn/walk.newErr(...)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/error.go:81
github.com/lxn/walk.newError(0x6ad3c7, 0xa, 0x0, 0x0)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/error.go:85 +0x2e
github.com/lxn/walk.lastError(0x6ad3c7, 0xa, 0x0, 0x1000000010)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/error.go:97 +0x132
github.com/lxn/walk.(*Icon).drawStretched(0xc000044600, 0xffffffffb4011cec, 0x0, 0x0, 0x10, 0x10, 0x0, 0x10)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/icon.go:322 +0xea
github.com/lxn/walk.(*Canvas).DrawImageStretched(0xc0000780a0, 0x6f5520, 0xc000044600, 0x0, 0x0, 0x10, 0x10, 0x1, 0x5ad)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/canvas.go:273 +0x1b9
github.com/lxn/walk.NewBitmapFromImageWithSize(0x6f5520, 0xc000044600, 0x10, 0x10, 0x0, 0x0, 0x0)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/bitmap.go:151 +0x258
github.com/lxn/walk.newIconFromImageForDPI(0x6f5520, 0xc000044600, 0x60, 0x0, 0x0, 0x0)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/icon.go:164 +0xd4
github.com/lxn/walk.(*IconCache).Icon(0xc000042560, 0x6f5520, 0xc000044600, 0x60, 0x1f907a58d46c06ce, 0x0, 0xc000075f20)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/iconcache.go:82 +0xc4
github.com/lxn/walk.(*NotifyIcon).setNIDIcon(0xc0000a01b0, 0xc000075b50, 0x6f5520, 0xc000044600, 0xb0cd4, 0x900000000)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/notifyicon.go:294 +0x69
github.com/lxn/walk.(*NotifyIcon).SetIcon(0xc0000a01b0, 0x6f5520, 0xc000044600, 0x0, 0x0)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/notifyicon.go:278 +0x1a0
```

A [DrawIconEx call](https://github.com/lxn/walk/blob/015262c282d682cc5dbff309d2b26677a0d82154/icon.go#L321) seems to be failing because it's trying to use an invalid handle returned by `handleForDPI`:

```
func (i *Icon) drawStretched(hdc win.HDC, bounds Rectangle) error {
	dpi := int(float64(bounds.Width) / float64(i.size96dpi.Width) * 96.0)

	hIcon := i.handleForDPI(dpi)

	if !win.DrawIconEx(hdc, int32(bounds.X), int32(bounds.Y), hIcon, int32(bounds.Width), int32(bounds.Height), 0, 0, win.DI_NORMAL) {
		return lastError("DrawIconEx")
	}

	return nil
}
```

The [handleForDPI](https://github.com/lxn/walk/blob/015262c282d682cc5dbff309d2b26677a0d82154/icon.go#L221) function is hiding an error. I tinkered with `drawStretched` to call `handleForDPIWithError` instead:

```
	hIcon, err := i.handleForDPIWithError(dpi)
	if err != nil {
		return fmt.Errorf("drawStretched: Handle For DPI %v: %v", dpi, err)
	}
```

Then I got this stack trace:

```
drawStretched: Handle For DPI 96: LoadImage

Stack:
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0x7fff62da6780, 0x0, 0x0)
        c:/go/src/runtime/debug/stack.go:24 +0xa4
github.com/lxn/walk.newErr(...)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/error.go:81
github.com/lxn/walk.newError(0x6adff0, 0x9, 0x6, 0x400000)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/error.go:85 +0x2e
github.com/lxn/walk.lastError(0x6adff0, 0x9, 0x1000000001, 0x10)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/error.go:97 +0x132
github.com/lxn/walk.(*Icon).handleForDPIWithError(0xc00005e5c0, 0x60, 0x408bad, 0x952e20, 0x621360)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/icon.go:289 +0x259
github.com/lxn/walk.(*Icon).drawStretched(0xc00005e5c0, 0x46010d90, 0x0, 0x0, 0x10, 0x10, 0x0, 0x10)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/icon.go:320 +0x82
github.com/lxn/walk.(*Canvas).DrawImageStretched(0xc0000920a0, 0x6f65a0, 0xc00005e5c0, 0x0, 0x0, 0x10, 0x10, 0x1, 0x5ad)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/canvas.go:273 +0x1b9
github.com/lxn/walk.NewBitmapFromImageWithSize(0x6f65a0, 0xc00005e5c0, 0x10, 0x10, 0x0, 0x0, 0x0)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/bitmap.go:151 +0x258
github.com/lxn/walk.newIconFromImageForDPI(0x6f65a0, 0xc00005e5c0, 0x60, 0x0, 0x0, 0x0)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/icon.go:165 +0xd4
github.com/lxn/walk.(*IconCache).Icon(0xc00004e550, 0x6f65a0, 0xc00005e5c0, 0x60, 0xc97108943a6c858d, 0x0, 0xc00008bf20)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/iconcache.go:82 +0xc4
github.com/lxn/walk.(*NotifyIcon).setNIDIcon(0xc0000ba1b0, 0xc00008bb50, 0x6f65a0, 0xc00005e5c0, 0xc0cd4, 0x900000000)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/notifyicon.go:294 +0x69
github.com/lxn/walk.(*NotifyIcon).SetIcon(0xc0000ba1b0, 0x6f65a0, 0xc00005e5c0, 0x0, 0x0)
        C:/Users/joshua.sjoding/go/src/github.com/lxn/walk/notifyicon.go:278 +0x1a0
```

It looks like [a LoadImage call](https://github.com/lxn/walk/blob/015262c282d682cc5dbff309d2b26677a0d82154/icon.go#L280) in [handleForDPIWithError](https://github.com/lxn/walk/blob/015262c282d682cc5dbff309d2b26677a0d82154/icon.go#L226) is failing. I'm not sure why.

**Comment by lxn** [comment]
Thanks for the detailed report. This should be fixed by https://github.com/lxn/walk/commit/3b9dbc29e91646ce796bdc2e0fbcdfaa769cc927.

**Comment by JoshuaSjoding** [comment]
Thanks!
