### ISSUE TITLE
GetMessage syscall.Syscall6 Crash

### ISSUE THREAD

**Issue by zhaoya881010** [lxn/walk#718]
golang version 1.15
Windows server 2012
Exception 0xc0000005 0x0 0x1749111c 0x77e47594
PC=0x77e47594
signal arrived during external code execution

syscall.Syscall6(0x7598a5b0, 0x4, 0x27066f8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
C:/Go/src/runtime/syscall_windows.go:201 +0xbb
GoProxy/vendor/github.com/lxn/win.GetMessage(0x27066f8, 0x0, 0x0, 0x0, 0x1)
D:/svn_code/src/GoProxy/vendor/github.com/lxn/win/user32.go:2564 +0x8a
GoProxy/vendor/github.com/lxn/walk.(*FormBase).mainLoop(0x2eb9a000, 0x0)
D:/svn_code/src/GoProxy/vendor/github.com/lxn/walk/mainloop_default.go:20 +0x95
GoProxy/vendor/github.com/lxn/walk.(*FormBase).Run(0x2eb9a000, 0x0)
D:/svn_code/src/GoProxy/vendor/github.com/lxn/walk/form.go:373 +0xa3
main.main()

No problem has been found in win7 environment for the time being. This problem has been found in 2012 server. It's not a startup error, it's other groutines that call programs with a desktop.

**Comment by zhaoya881010** [comment]
goroutine 54 [syscall, locked to thread]:
syscall.Syscall(0x77689050, 0x2, 0x92c, 0xffffffff, 0x0, 0x0, 0x0, 0x0)
	C:/go-build/Go/src/runtime/syscall_windows.go:172 +0xcf
syscall.WaitForSingleObject(0x92c, 0xffffffff, 0x0, 0x0, 0x0)
	C:/go-build/Go/src/syscall/zsyscall_windows.go:737 +0x53
os.(*Process).wait(0x2e936930, 0x0, 0x0, 0x0)
	C:/go-build/Go/src/os/exec_windows.go:18 +0x5a
os.(*Process).Wait(0x2e936930, 0x2e820600, 0x0, 0x0)
	C:/go-build/Go/src/os/exec.go:125 +0x21
os/exec.(*Cmd).Wait(0x2ebc8210, 0xb6bea8, 0x0)
	C:/go-build/Go/src/os/exec/exec.go:465 +0x43
GoProxy/utils/shell.RunCmdWithTimeout.func5(0x2ebc8210, 0x2e92605c, 0x2eb0e1c0, 0x2eba3d00, 0x2eb8a000, 0x24)
	D:/gseeproxy/src/GoProxy/utils/shell/shell.go:204 +0x43
created by GoProxy/utils/shell.RunCmdWithTimeout
	D:/gseeproxy/src/GoProxy/utils/shell/shell.go:198 +0x7f4
eax     0xffffffff
ebx     0x0
ecx     0x30
edx     0x0
edi     0x24
esi     0x1
ebp     0xffffffff
esp     0x0
eip     0x77e47594
eflags  0x0
cs      0x0
fs      0x14f63580
gs      0xbfd70d2f
